[package]
name = "xmlreader"
version = "0.1.0"
authors = ["Claude Glauser <public@claude-glauser.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmltree = "0.10"
xml-rs = "0.8"